DROP TABLE IF EXISTS TICKETS;
DROP TABLE IF EXISTS ADMINS;
CREATE TABLE TICKETS (
ticket_id INT AUTO_INCREMENT  PRIMARY KEY,
sender_name VARCHAR(50) NOT NULL,
content VARCHAR(150) NOT NULL,
status VARCHAR(50) NOT NULL,
admin_id INT(3) NULL
);
CREATE TABLE ADMINS (
admin_id INT AUTO_INCREMENT  PRIMARY KEY,
admin_name VARCHAR(50) NOT NULL,
resolved_count INT(3) NOT NULL
);

