package com.fresco.springtickets.models;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "tickets")
public class Ticket {

    /**
     * This is a model for Ticket which is also used to
     * connect to the database
     * TODO Annotate with revelant annotations for making "ticket" table
     */

    /*
    ticket_id is the primary key for the "ticket" table
    and should be autogenerated integer
     */
    @Id
	@GeneratedValue(strategy = GenerationType.AUTO)
    private int ticket_id;

    private String sender_name;

    private String status;

    private String content;

    //@Column(name = "admin_id")
    private int admin_id;

}
